### ISSUE TITLE
undefined value puts and doesExist error

### ISSUE THREAD

**Issue by TimDaub** [kriszyp/lmdbx-store#17]
- I had used db.put(key) without a value to store unique hashes in a db
- I had then used db.doesExist(key) to verify if a hash had already been added to a DB
- however, without really understanding why, I sometimes got false positives for a hash that I actually hadn't put in the db but where db.doesExist(key) returned true
- What could have caused this:
  - I used a mix of hexadecimals and strings as the key: https://github.com/attestate/kiwistand/blob/15da2ca3c7649f6519c0af24f67bb426f70e5865/src/store.mjs#L237
  - Since I used only put(key), value was undefined: https://github.com/attestate/kiwistand/blob/15da2ca3c7649f6519c0af24f67bb426f70e5865/src/store.mjs#L239

How I fixed it now: I migrated all keys to db.put(key, true) and I'm now using 

```
const notFound = (await db.get(key)) === undefined;
```

instead of 

https://github.com/attestate/kiwistand/blob/15da2ca3c7649f6519c0af24f67bb426f70e5865/src/store.mjs#L238

This seems to have addressed my issue. Would love to understand why doesExist matches false positives. Is the matching greedy?

**Comment by kriszyp** [comment]
I am not able to reproduce this, doesExist seems to work with strings with hexadecimals, and put works without a second argument. Do you have a test case that reproduces this issue?

**Comment by TimDaub** [comment]
I will share the lmdb with you later

**Comment by TimDaub** [comment]
Actually I tried reproducing and found that I had a misunderstanding: https://github.com/TimDaub/lmdb-reproduce. I got confused, considering that db.get(key) can return a value like "undefined," I thought that meant the value wasn't found in the database. But since put(key) can be used without defining a value, a key can be defined but its value can be undefined.
