### ISSUE TITLE
Uint8Array has no readUInt16BE 

### ISSUE THREAD

**Issue by gcxfd** [kriszyp/lmdbx-store#4]
https://github.com/kriszyp/lmdbx-store/blob/45c76ca501b873724547119932bd7c95b69ee6cb/index.js#L336
https://github.com/kriszyp/lmdbx-store/blob/45c76ca501b873724547119932bd7c95b69ee6cb/index.js#L368

as title , maybe use .buffer ? both Buffer and Uint8Array has this

**Comment by kriszyp** [comment]
I have upgraded this to the latest from lmdb-js 2.0, which I think eliminates this error.
